path: ../Data
train: train
val: test  

# Classes
names:
  0: 0
  1: 1
  2: 2
  3: 3
  4: 4
  5: 5
  6: 6
  7: 7
  8: 8
  9: 9
  10: A
  11: B
  12: D
  13: E
  14: G
  15: H
  16: J
  17: K
  18: L
  19: N
  20: R
  21: S
  22: T
  23: U
  24: V
  25: X
  26: Z